[ { created_at: 'Wed Apr 29 10:42:42 +0000 2020',
    id: 1255447409498501000,
    id_str: '1255447409498501120',
    text:
     'RT @SandalsAnew: The "testing" has been proven faulty and tainted.\nWhat is so Important about "testing" ?\n\nFrom the likes of the control, d…',
    truncated: false,
    entities:
     { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1051800858940330000,
       id_str: '1051800858940329985',
       name: '���Lindy-USA���',
       screen_name: 'UsaLindy',
       location: 'Best Constitutional Republic',
       description:
        'Child of #God, Mom, #Patriot, Seeker of #Truth; #QAnon, #Cult45, #MAGA, #WWG1WGA ��� #TheConstitution! #UpCountry\n\nI don\'t hesitate
to block bots and trolls.',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 10966,
       friends_count: 11100,
       listed_count: 3,
       created_at: 'Mon Oct 15 11:44:01 +0000 2018',
       favourites_count: 28715,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 25191,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1231010673708191747/yeGnttGw_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1231010673708191747/yeGnttGw_normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/1051800858940329985/1581382057',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Tue Apr 28 20:39:08 +0000 2020',
       id: 1255235118521868300,
       id_str: '1255235118521868293',
       text:
        'The "testing" has been proven faulty and tainted.\nWhat is so Important about "testing" ?\n\nFrom the likes of the con… https://t.co/ZiAOfg4cDR',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: true,
       quoted_status_id: 1255229969346769000,
       quoted_status_id_str: '1255229969346768902',
       quoted_status: [Object],
       retweet_count: 10,
       favorite_count: 7,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: true,
    quoted_status_id: 1255229969346769000,
    quoted_status_id_str: '1255229969346768902',
    retweet_count: 10,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:42:19 +0000 2020',
    id: 1255447313583165400,
    id_str: '1255447313583165440',
    text:
     '@KTHopkins Mandatory???  No way.  I’d definitely take it, if it was voluntary, and was developed, tested, and manuf… https://t.co/HWhVkkopTu',
    truncated: true,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions: [Array],
       urls: [Array] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 1255388957191307300,
    in_reply_to_status_id_str: '1255388957191307265',
    in_reply_to_user_id: 21439144,
    in_reply_to_user_id_str: '21439144',
    in_reply_to_screen_name: 'KTHopkins',
    user:
     { id: 748351285703761900,
       id_str: '748351285703761920',
       name: 'Deedee��',
       screen_name: '_GravityFails',
       location: 'Dexter\'s Laboratory, \'Course�',
       description:
        'URGENT: Are you Type "O" Blood Group? If so, please save a young man\'s life today. Please consider donating 1 kidney to save a precious life: 850-557-3522.',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 829,
       friends_count: 2760,
       listed_count: 6,
       created_at: 'Thu Jun 30 03:03:45 +0000 2016',
       favourites_count: 57256,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 42618,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1231703109228851201/RRp5Blm__normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1231703109228851201/RRp5Blm__normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/748351285703761920/1507765847',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:40:07 +0000 2020',
    id: 1255446760102809600,
    id_str: '1255446760102809603',
    text:
     'RT @Utsava4: ... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks ago, he has…',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 760560524492992500,
       id_str: '760560524492992516',
       name: 'abdalazez������',
       screen_name: 'lovemadrista2',
       location: 'Loire, Rhône-Alpes',
       description:
        'مدير قروب سابق عاشق للسفر كثير الترحال في بلاد الله الواسعه واحب الموسيقى والطبخ واعزف بيانو ملم في السياسه ولعبة المقصى وقليلاً من الك
يرم واحب المرقوق',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 162,
       friends_count: 983,
       listed_count: 0,
       created_at: 'Tue Aug 02 19:38:54 +0000 2016',
       favourites_count: 2822,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4894,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1163920128184115205/rgG1at6A_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1163920128184115205/rgG1at6A_normal.jpg',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 07:48:24 +0000 2020',
       id: 1255403547304366000,
       id_str: '1255403547304366081',
       text:
        '... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks… https://t.co/6NRqEGKl6g',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 42,
       favorite_count: 122,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 42,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:39:36 +0000 2020',
    id: 1255446628976263200,
    id_str: '1255446628976263169',
    text:
     '@DelilahSarah @gatesfoundation @BillGates Also was best buddies with Epstein. It’s like that information is blocked from people’s minds.',
    truncated: false,
    entities:
     { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 1255345912500682800,
    in_reply_to_status_id_str: '1255345912500682752',
    in_reply_to_user_id: 80821973,
    in_reply_to_user_id_str: '80821973',
    in_reply_to_screen_name: 'DelilahSarah',
    user:
     { id: 1254873877081026600,
       id_str: '1254873877081026560',
       name: 'Neo22',
       screen_name: 'Neo2210259194',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 1,
       friends_count: 14,
       listed_count: 0,
       created_at: 'Mon Apr 27 20:43:53 +0000 2020',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 7,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1255196010634113024/O5X5iP2p_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1255196010634113024/O5X5iP2p_normal.jpg',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:36:16 +0000 2020',
    id: 1255445791562399700,
    id_str: '1255445791562399745',
    text:
     'RT @Utsava4: ... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks ago, he has…',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 3383537247,
       id_str: '3383537247',
       name: 'Monica Hunter',
       screen_name: 'murbanietz',
       location: '',
       description: 'Pro-life, nationalist, Trump supporter',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 190,
       friends_count: 453,
       listed_count: 0,
       created_at: 'Sun Jul 19 20:46:55 +0000 2015',
       favourites_count: 20326,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 17326,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1241805265168740352/auPFePfT_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1241805265168740352/auPFePfT_normal.jpg',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 07:48:24 +0000 2020',
       id: 1255403547304366000,
       id_str: '1255403547304366081',
       text:
        '... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks… https://t.co/6NRqEGKl6g',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 42,
       favorite_count: 122,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 42,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:35:08 +0000 2020',
    id: 1255445505703903200,
    id_str: '1255445505703903242',
    text:
     'RT @Egg1e7: @QuietBearCoin @Jhwrr @BillGates I agree and there still trying to suck money from the world and push their \'vaxs\'!!!',
    truncated: false,
    entities:
     { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1928724222,
       id_str: '1928724222',
       name: 'Bear',
       screen_name: 'QuietBearCoin',
       location: 'Earth',
       description:
        'Hubby of Marcela, Dad of Michael, Matt & Missy. Grandpa of Austin, Caleb & Will\nUSAF, Defender of the Constitution, Artist, Shaman & Organic Farmer',
       url: 'https://t.co/2phWYQbM00',
       entities: [Object],
       protected: false,
       followers_count: 5224,
       friends_count: 5560,
       listed_count: 5,
       created_at: 'Thu Oct 03 00:48:35 +0000 2013',
       favourites_count: 28446,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: false,
       statuses_count: 52370,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '000000',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1025996376931332101/D7bjmQFa_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1025996376931332101/D7bjmQFa_normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/1928724222/1555881984',
       profile_link_color: '1B95E0',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: '000000',
       profile_text_color: '000000',
       profile_use_background_image: false,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 07:00:29 +0000 2020',
       id: 1255391489389138000,
       id_str: '1255391489389137921',
       text:
        '@QuietBearCoin @Jhwrr @BillGates I agree and there still trying to suck money from the world and push their \'vaxs\'!!!',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: 1255389395575804000,
       in_reply_to_status_id_str: '1255389395575803905',
       in_reply_to_user_id: 1928724222,
       in_reply_to_user_id_str: '1928724222',
       in_reply_to_screen_name: 'QuietBearCoin',
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:34:38 +0000 2020',
    id: 1255445378817839000,
    id_str: '1255445378817839105',
    text:
     'RT @Utsava4: ... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks ago, he has…',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 999042853564231700,
       id_str: '999042853564231681',
       name: 'Mirjana Kubicek',
       screen_name: 'KubicekMirjana',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 75,
       friends_count: 23,
       listed_count: 0,
       created_at: 'Tue May 22 21:42:32 +0000 2018',
       favourites_count: 42646,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 38457,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_image_url_https:
        'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: true,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 07:48:24 +0000 2020',
       id: 1255403547304366000,
       id_str: '1255403547304366081',
       text:
        '... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks… https://t.co/6NRqEGKl6g',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 42,
       favorite_count: 122,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 42,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:33:58 +0000 2020',
    id: 1255445211087540200,
    id_str: '1255445211087540225',
    text:
     'RT @Utsava4: ... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks ago, he has…',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1181392321603981300,
       id_str: '1181392321603981314',
       name: 'twatterfly4Justice',
       screen_name: 'twatterfly24',
       location: '',
       description:
        'Patriot! Fighter for Justice! Seeks Truth! Believes in Q and loves TRUMP! #greatestpresidentever #epsteindidntkillhimself',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 277,
       friends_count: 286,
       listed_count: 0,
       created_at: 'Tue Oct 08 02:14:39 +0000 2019',
       favourites_count: 2631,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 1840,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1193822860910850049/jWOx4p0H_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1193822860910850049/jWOx4p0H_normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/1181392321603981314/1573175574',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 07:48:24 +0000 2020',
       id: 1255403547304366000,
       id_str: '1255403547304366081',
       text:
        '... involved in spreading corona. I also predicted that the arrest of #BillGates is coming up and said a few weeks… https://t.co/6NRqEGKl6g',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 42,
       favorite_count: 122,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 42,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:33:41 +0000 2020',
    id: 1255445140312928300,
    id_str: '1255445140312928259',
    text:
     'RT @DumpCuomo: @TheRightMelissa I’m not taking medical or vaccine advice from an I.T. Guy ie #BillGates',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1162764369530433500,
       id_str: '1162764369530433537',
       name: 'John Haas',
       screen_name: 'JohnHaa52841778',
       location: 'Western North Carolina, USA',
       description:
        'Married, father, Christian, Conservative, Truth and Facts always Trump Feelings, ⚠️If you don\'t like Trump, you definitely won\'t like
 me!!!��\n#KAG #TRUMP2020',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 989,
       friends_count: 1387,
       listed_count: 0,
       created_at: 'Sat Aug 17 16:35:21 +0000 2019',
       favourites_count: 7288,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4786,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1246567253493067776/1RdqBM7N_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1246567253493067776/1RdqBM7N_normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/1162764369530433537/1585520807',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Wed Apr 29 10:04:31 +0000 2020',
       id: 1255437799848849400,
       id_str: '1255437799848849408',
       text:
        '@TheRightMelissa I’m not taking medical or vaccine advice from an I.T. Guy ie #BillGates',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: 1255243571592073200,
       in_reply_to_status_id_str: '1255243571592073220',
       in_reply_to_user_id: 762389795037294600,
       in_reply_to_user_id_str: '762389795037294592',
       in_reply_to_screen_name: 'TheRightMelissa',
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 1,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Wed Apr 29 10:32:51 +0000 2020',
    id: 1255444933789573000,
    id_str: '1255444933789573125',
    text:
     'Why @BillGates hasn\'t joined @Conf_of_Pres or is he part of it? Are you busy saving the world from #coronavirus or… https://t.co/oIBxUtpAa8',
    truncated: true,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [Array],
       urls: [Array] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source:
     '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 1191951901350334500,
       id_str: '1191951901350334465',
       name: 'Open Genesis',
       screen_name: 'open_genesis',
       location: 'USA',
       description:
        'Reaching out to World Leaders was the beginning of 2019 and the world started to change. I am a Copt #Coptic #Taurus ☩ ♉. Wait for the
Lord #open_genesis',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 37,
       friends_count: 461,
       listed_count: 0,
       created_at: 'Wed Nov 06 05:34:21 +0000 2019',
       favourites_count: 337,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 2380,
       lang: null,
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url:
        'http://pbs.twimg.com/profile_images/1223262370404892674/HxVoK0p3_normal.jpg',
       profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1223262370404892674/HxVoK0p3_normal.jpg',
       profile_banner_url:
        'https://pbs.twimg.com/profile_banners/1191951901350334465/1573019344',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' } ]
